package net.suncaper.demo.domain;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.cart_id
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    private String cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.num_product
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    private Integer numProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_mailaddress
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    private String userMailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.product_id
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public Cart(String cartId, Integer numProduct, String userMailaddress, String productId) {
        this.cartId = cartId;
        this.numProduct = numProduct;
        this.userMailaddress = userMailaddress;
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public Cart() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.cart_id
     *
     * @return the value of cart.cart_id
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public String getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.cart_id
     *
     * @param cartId the value for cart.cart_id
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public void setCartId(String cartId) {
        this.cartId = cartId == null ? null : cartId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.num_product
     *
     * @return the value of cart.num_product
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public Integer getNumProduct() {
        return numProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.num_product
     *
     * @param numProduct the value for cart.num_product
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public void setNumProduct(Integer numProduct) {
        this.numProduct = numProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_mailaddress
     *
     * @return the value of cart.user_mailaddress
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public String getUserMailaddress() {
        return userMailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_mailaddress
     *
     * @param userMailaddress the value for cart.user_mailaddress
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public void setUserMailaddress(String userMailaddress) {
        this.userMailaddress = userMailaddress == null ? null : userMailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.product_id
     *
     * @return the value of cart.product_id
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.product_id
     *
     * @param productId the value for cart.product_id
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Cart other = (Cart) that;
        return (this.getCartId() == null ? other.getCartId() == null : this.getCartId().equals(other.getCartId()))
            && (this.getNumProduct() == null ? other.getNumProduct() == null : this.getNumProduct().equals(other.getNumProduct()))
            && (this.getUserMailaddress() == null ? other.getUserMailaddress() == null : this.getUserMailaddress().equals(other.getUserMailaddress()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sat Jun 29 15:46:45 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCartId() == null) ? 0 : getCartId().hashCode());
        result = prime * result + ((getNumProduct() == null) ? 0 : getNumProduct().hashCode());
        result = prime * result + ((getUserMailaddress() == null) ? 0 : getUserMailaddress().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        return result;
    }
}