package net.suncaper.demo.domain;

public class CartProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.cart_id
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private String cartId;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.num_product
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private Integer numProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_mailaddress
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private String userMailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.product_id
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private String productId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.producer
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private String producer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.producing_area
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private String producingArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private Long stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Thu Jun 27 21:58:42 CST 2019
     */
    private Integer price;

    public CartProduct(String cartId, Integer numProduct, String userMailaddress, String productId, String productName, String producer, String producingArea, Long stock, String type, Integer price) {
        this.cartId = cartId;
        this.numProduct = numProduct;
        this.userMailaddress = userMailaddress;
        this.productId = productId;
        this.productName = productName;
        this.producer = producer;
        this.producingArea = producingArea;
        this.stock = stock;
        this.type = type;
        this.price = price;
    }

    public String getCartId() {
        return cartId;
    }

    public void setCartId(String cartId) {
        this.cartId = cartId;
    }

    public Integer getNumProduct() {
        return numProduct;
    }

    public void setNumProduct(Integer numProduct) {
        this.numProduct = numProduct;
    }

    public String getUserMailaddress() {
        return userMailaddress;
    }

    public void setUserMailaddress(String userMailaddress) {
        this.userMailaddress = userMailaddress;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProducer() {
        return producer;
    }

    public void setProducer(String producer) {
        this.producer = producer;
    }

    public String getProducingArea() {
        return producingArea;
    }

    public void setProducingArea(String producingArea) {
        this.producingArea = producingArea;
    }

    public Long getStock() {
        return stock;
    }

    public void setStock(Long stock) {
        this.stock = stock;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }
}
