package net.suncaper.demo.domain;

import java.util.ArrayList;
import java.util.List;

public class DeliveryAddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public DeliveryAddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressIsNull() {
            addCriterion("user_mailaddress is null");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressIsNotNull() {
            addCriterion("user_mailaddress is not null");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressEqualTo(String value) {
            addCriterion("user_mailaddress =", value, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressNotEqualTo(String value) {
            addCriterion("user_mailaddress <>", value, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressGreaterThan(String value) {
            addCriterion("user_mailaddress >", value, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressGreaterThanOrEqualTo(String value) {
            addCriterion("user_mailaddress >=", value, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressLessThan(String value) {
            addCriterion("user_mailaddress <", value, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressLessThanOrEqualTo(String value) {
            addCriterion("user_mailaddress <=", value, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressLike(String value) {
            addCriterion("user_mailaddress like", value, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressNotLike(String value) {
            addCriterion("user_mailaddress not like", value, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressIn(List<String> values) {
            addCriterion("user_mailaddress in", values, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressNotIn(List<String> values) {
            addCriterion("user_mailaddress not in", values, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressBetween(String value1, String value2) {
            addCriterion("user_mailaddress between", value1, value2, "userMailaddress");
            return (Criteria) this;
        }

        public Criteria andUserMailaddressNotBetween(String value1, String value2) {
            addCriterion("user_mailaddress not between", value1, value2, "userMailaddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryaddress
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 01 14:33:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deliveryaddress
     *
     * @mbg.generated Mon Jul 01 14:33:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}