package net.suncaper.demo.domain;

public class DeliveryAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryaddress.id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryaddress.address
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryaddress.user_mailaddress
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    private String userMailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryaddress.user_phone
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryaddress.name
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public DeliveryAddress(Integer id, String address, String userMailaddress, String userPhone, String name) {
        this.id = id;
        this.address = address;
        this.userMailaddress = userMailaddress;
        this.userPhone = userPhone;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public DeliveryAddress() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryaddress.id
     *
     * @return the value of deliveryaddress.id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryaddress.id
     *
     * @param id the value for deliveryaddress.id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryaddress.address
     *
     * @return the value of deliveryaddress.address
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryaddress.address
     *
     * @param address the value for deliveryaddress.address
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryaddress.user_mailaddress
     *
     * @return the value of deliveryaddress.user_mailaddress
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public String getUserMailaddress() {
        return userMailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryaddress.user_mailaddress
     *
     * @param userMailaddress the value for deliveryaddress.user_mailaddress
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public void setUserMailaddress(String userMailaddress) {
        this.userMailaddress = userMailaddress == null ? null : userMailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryaddress.user_phone
     *
     * @return the value of deliveryaddress.user_phone
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryaddress.user_phone
     *
     * @param userPhone the value for deliveryaddress.user_phone
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryaddress.name
     *
     * @return the value of deliveryaddress.name
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryaddress.name
     *
     * @param name the value for deliveryaddress.name
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DeliveryAddress other = (DeliveryAddress) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getUserMailaddress() == null ? other.getUserMailaddress() == null : this.getUserMailaddress().equals(other.getUserMailaddress()))
            && (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(other.getUserPhone()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryaddress
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getUserMailaddress() == null) ? 0 : getUserMailaddress().hashCode());
        result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        return result;
    }
}