package net.suncaper.demo.domain;

public class PaymentRecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentrecord.record_id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentrecord.orders_id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    private String ordersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentrecord.build_day
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    private String buildDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentrecord
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public PaymentRecordKey(String recordId, String ordersId, String buildDay) {
        this.recordId = recordId;
        this.ordersId = ordersId;
        this.buildDay = buildDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentrecord
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public PaymentRecordKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentrecord.record_id
     *
     * @return the value of paymentrecord.record_id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentrecord.record_id
     *
     * @param recordId the value for paymentrecord.record_id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentrecord.orders_id
     *
     * @return the value of paymentrecord.orders_id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public String getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentrecord.orders_id
     *
     * @param ordersId the value for paymentrecord.orders_id
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public void setOrdersId(String ordersId) {
        this.ordersId = ordersId == null ? null : ordersId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentrecord.build_day
     *
     * @return the value of paymentrecord.build_day
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public String getBuildDay() {
        return buildDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentrecord.build_day
     *
     * @param buildDay the value for paymentrecord.build_day
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    public void setBuildDay(String buildDay) {
        this.buildDay = buildDay == null ? null : buildDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentrecord
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaymentRecordKey other = (PaymentRecordKey) that;
        return (this.getRecordId() == null ? other.getRecordId() == null : this.getRecordId().equals(other.getRecordId()))
            && (this.getOrdersId() == null ? other.getOrdersId() == null : this.getOrdersId().equals(other.getOrdersId()))
            && (this.getBuildDay() == null ? other.getBuildDay() == null : this.getBuildDay().equals(other.getBuildDay()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentrecord
     *
     * @mbg.generated Fri Jul 05 09:58:59 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRecordId() == null) ? 0 : getRecordId().hashCode());
        result = prime * result + ((getOrdersId() == null) ? 0 : getOrdersId().hashCode());
        result = prime * result + ((getBuildDay() == null) ? 0 : getBuildDay().hashCode());
        return result;
    }
}