server:
  port: 8180
mybatis:
  mapper-locations:  classpath:/mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver