package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.domain.customer;
import net.suncaper.demo.domain.customerExample;
import org.apache.ibatis.annotations.Param;

public interface customerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    long countByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    int deleteByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    int insert(customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    int insertSelective(customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    List<customer> selectByExampleWithBLOBs(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    List<customer> selectByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") customer record, @Param("example") customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") customer record, @Param("example") customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Jun 23 21:53:02 CST 2019
     */
    int updateByExample(@Param("record") customer record, @Param("example") customerExample example);
}