package net.suncaper.demo.mapper;

import java.util.List;
import net.suncaper.demo.domain.orders;
import net.suncaper.demo.domain.ordersExample;
import org.apache.ibatis.annotations.Param;

public interface ordersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    long countByExample(ordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    int deleteByExample(ordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    int deleteByPrimaryKey(String ordersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    int insert(orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    int insertSelective(orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    List<orders> selectByExample(ordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    orders selectByPrimaryKey(String ordersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") orders record, @Param("example") ordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    int updateByExample(@Param("record") orders record, @Param("example") ordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    int updateByPrimaryKeySelective(orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jun 24 20:58:56 CST 2019
     */
    int updateByPrimaryKey(orders record);
}